<option value="icon-glass">glass</option>
<option value="icon-music">music</option>
<option value="icon-search">search</option>
<option value="icon-envelope">envelope</option>
<option value="icon-heart">heart</option>
<option value="icon-star">star</option>
<option value="icon-star-empty">star-empty</option>
<option value="icon-user">user</option>
<option value="icon-film">film</option>
<option value="icon-th-large">th-large</option>
<option value="icon-th">th</option>
<option value="icon-th-list">th-list</option>
<option value="icon-ok">check</option>
<option value="icon-remove">remove</option>
<option value="icon-zoom-in">zoom in</option>

<option value="icon-zoom-out">zoom out</option>
<option value="icon-off">off</option>
<option value="icon-signal">signal</option>
<option value="icon-cog">cog</option>
<option value="icon-trash">trash</option>
<option value="icon-home">home</option>
<option value="icon-file">file</option>
<option value="icon-time">time</option>
<option value="icon-road">road</option>
<option value="icon-download">download</option>
<option value="icon-download-alt">download 2</option>
<option value="icon-upload">upload</option>
<option value="icon-inbox">inbox</option>
<option value="icon-play-circle">play circle</option>
<option value="icon-repeat">repeat</option>


<option value="icon-refresh">refresh</option>
<option value="icon-list-alt">list 2</option>
<option value="icon-lock">lock</option>
<option value="icon-flag">flag</option>
<option value="icon-headphones">headphone</option>
<option value="icon-volume-off">volume off</option>
<option value="icon-volume-down">volume down</option>
<option value="icon-volume-up">volume up</option>
<option value="icon-qrcode">qrcode</option>
<option value="icon-barcode">barcode</option>
<option value="icon-tag">tag</option>
<option value="icon-tags">tags</option>
<option value="icon-book">book</option>
<option value="icon-bookmark">bookmark</option>
<option value="icon-print">print</option>

<option value="icon-camera">camera</option>
<option value="icon-font">font</option>
<option value="icon-bold">bold</option>
<option value="icon-italic">italic</option>
<option value="icon-text-height">text height</option>
<option value="icon-text-width">text width</option>
<option value="icon-align-left">align left</option>
<option value="icon-align-center">align center</option>
<option value="icon-align-right">align right</option>
<option value="icon-align-justify">justify</option>
<option value="icon-list">list</option>
<option value="icon-indent-left">indent left</option>
<option value="icon-indent-right">indent right</option>
<option value="icon-facetime-video">video</option>
<option value="icon-picture">picture</option>

<option value="icon-pencil">pencil</option>
<option value="icon-map-marker">marker</option>
<option value="icon-adjust">adjust</option>
<option value="icon-tint">tint</option>
<option value="icon-edit">edit</option>
<option value="icon-share">share</option>
<option value="icon-check">check 3</option>
<option value="icon-move">move</option>
<option value="icon-step-backward">step backward</option>
<option value="icon-fast-backward">fast backward</option>
<option value="icon-backward">backward</option>
<option value="icon-play">play</option>
<option value="icon-pause">pause</option>
<option value="icon-stop">stop</option>
<option value="icon-forward">forward</option>

<option value="icon-fast-forward">fast forward</option>
<option value="icon-step-forward">step forward</option>
<option value="icon-eject">eject</option>
<option value="icon-chevron-left">chevron left</option>
<option value="icon-chevron-right">chevron right</option>
<option value="icon-plus-sign">plus sign</option>
<option value="icon-minus-sign">minus sign</option>
<option value="icon-remove-sign"> remove 2</option>
<option value="icon-ok-sign"> check 2</option>
<option value="icon-question-sign">question sign</option>
<option value="icon-info-sign">info sign</option>
<option value="icon-screenshot">screenshot</option>
<option value="icon-remove-circle">remove circle</option>
<option value="icon-ok-circle"> check circle</option>
<option value="icon-ban-circle">ban circle</option>

<option value="icon-arrow-left"> arrow left</option>
<option value="icon-arrow-right">arrow right</option>
<option value="icon-arrow-up">arrow up</option>
<option value="icon-arrow-down">arrow down</option>
<option value="icon-share-alt">share 2</option>
<option value="icon-resize-full">resize full</option>
<option value="icon-resize-small">resize small</option>
<option value="icon-plus">plus</option>
<option value="icon-minus">minus</option>
<option value="icon-asterisk">asterisk</option>
<option value="icon-exclamation-sign">exclamation sign</option>
<option value="icon-gift">gift</option>
<option value="icon-leaf">leaf</option>
<option value="icon-fire">fire</option>
<option value="icon-eye-open">eye open</option>

<option value="icon-eye-close">eye close</option>
<option value="icon-warning-sign">warning sign</option>
<option value="icon-plane">plane</option>
<option value="icon-calendar">calendar</option>
<option value="icon-random">random</option>
<option value="icon-comment">comment</option>
<option value="icon-magnet">magnet</option>
<option value="icon-chevron-up">chevron up</option>
<option value="icon-chevron-down">chevron down</option>
<option value="icon-retweet">retweet</option>
<option value="icon-shopping-cart">shopping cart</option>
<option value="icon-folder-close">folder close</option>
<option value="icon-folder-open">folder open</option>
<option value="icon-resize-vertical">resize vertical</option>
<option value="icon-resize-horizontal">resize horizontal</option>

<option value="icon-bar-chart">bar chart </option>
<option value="icon-twitter-sign">twitter sign</option>
<option value="icon-facebook-sign">facebook sign</option>
<option value="icon-camera-retro">camera retro</option>
<option value="icon-key">key</option>
<option value="icon-cogs">cogs</option>
<option value="icon-comments">comments</option>
<option value="icon-thumbs-up">thumbs up</option>
<option value="icon-thumbs-down">thumbs down</option>
<option value="icon-star-half">star half</option>
<option value="icon-heart-empty">heart empty</option>
<option value="icon-signout">signout</option>
<option value="icon-linkedin-sign">linkedin sign</option>
<option value="icon-pushpin">pushpin</option>
<option value="icon-external-link">link</option>

<option value="icon-signin">sign in</option>
<option value="icon-trophy">trophy</option>
<option value="icon-github-sign">github sign</option>
<option value="icon-upload-alt">upload 2</option>
<option value="icon-lemon">lemon</option>
<option value="icon-phone">phone</option>
<option value="icon-check-empty">check empty</option>
<option value="icon-bookmark-empty">bookmark empty</option>
<option value="icon-phone-sign">phone sign</option>
<option value="icon-twitter">twitter</option>
<option value="icon-facebook">facebook</option>
<option value="icon-github">github</option>
<option value="icon-unlock">unloack</option>
<option value="icon-credit-card">credit card</option>
<option value="icon-rss">rss</option>

<option value="icon-hdd">hdd</option>
<option value="icon-bullhorn">bullhorn</option>
<option value="icon-bell">bell</option>
<option value="icon-certificate">certificate</option>
<option value="icon-hand-right">hand right</option>
<option value="icon-hand-left">hand left</option>
<option value="icon-hand-up">hand up</option>
<option value="icon-hand-down">hand down</option>
<option value="icon-circle-arrow-left">arrow left circle</option>
<option value="icon-circle-arrow-right">arrow right circle</option>
<option value="icon-circle-arrow-up">arrow up circle</option>
<option value="icon-circle-arrow-down">arrow down circle</option>
<option value="icon-globe">globe</option>
<option value="icon-wrench">wrench</option>
<option value="icon-tasks">tasks</option>

<option value="icon-filter">filter</option>
<option value="icon-briefcase">briefcase</option>
<option value="icon-fullscreen">fullscreen</option>

<option value="icon-group">group</option>
<option value="icon-link">link</option>
<option value="icon-cloud">cloud</option>
<option value="icon-beaker">beaker</option>
<option value="icon-cut">cut</option>
<option value="icon-copy">copy</option>
<option value="icon-paper-clip">paper clip</option>
<option value="icon-save">save</option>
<option value="icon-sign-blank">sign</option>
<option value="icon-reorder">reorder</option>
<option value="icon-list-ul">list ul</option>
<option value="icon-list-ol">list ol</option>
<option value="icon-strikethrough">strikethrough</option>
<option value="icon-underline">underline</option>
<option value="icon-table">table</option>

<option value="icon-magic">magic</option>
<option value="icon-truck">truck</option>
<option value="icon-pinterest">pinterest</option>
<option value="icon-pinterest-sign">pinterest sign</option>
<option value="icon-google-plus-sign"> google plus sign</option>
<option value="icon-google-plus">google plus</option>
<option value="icon-money">money</option>
<option value="icon-caret-down">caret down</option>
<option value="icon-caret-up">caret up</option>
<option value="icon-caret-left">caret left</option>
<option value="icon-caret-right">caret right</option>
<option value="icon-columns">columns</option>
<option value="icon-sort">sort</option>
<option value="icon-sort-down">sort down</option>
<option value="icon-sort-up">sort up</option>

<option value="icon-envelope-alt">envelope 2</option>
<option value="icon-linkedin">linkedin</option>
<option value="icon-undo">undo</option>
<option value="icon-legal">legal</option>
<option value="icon-dashboard">dashboard</option>
<option value="icon-comment-alt">comment 2</option>
<option value="icon-comments-alt">comments 2</option>
<option value="icon-bolt">bolt</option>
<option value="icon-sitemap">sitemap</option>
<option value="icon-umbrella">umprella</option>
<option value="icon-paste">paste</option>


<option value="icon-cloud-download">cloud-download</option>
<option value="icon-cloud-upload">cloud-upload</option>
<option value="icon-lightbulb">lightbulb</option>
<option value="icon-exchange">exchange</option>
<option value="icon-bell-alt">bell-alt</option>
<option value="icon-file-alt">file-alt</option>
<option value="icon-beer">beer</option>
<option value="icon-coffee">coffee</option>
<option value="icon-food">food</option>
<option value="icon-fighter-jet">fighter-jet</option>
<option value="icon-user-md">user-md</option>
<option value="icon-stethoscope">stethoscope</option>
<option value="icon-suitcase">suitcase</option>
<option value="icon-building">building</option>
<option value="icon-hospital">hospital</option>
<option value="icon-ambulance">ambulance</option>
<option value="icon-medkit">medkit</option>
<option value="icon-h-sign">icon-h-sign</option>
<option value="icon-plus-sign-alt">plus-sign-alt</option>
<option value="icon-spinner">spinner</option>
<option value="icon-angle-left">angle-left</option>
<option value="icon-angle-right">angle-right</option>
<option value="icon-angle-up">angle-up</option>
<option value="icon-angle-down">angle-down</option>
<option value="icon-double-angle-left">double-angle-left</option>
<option value="icon-double-angle-right">double-angle-right</option>
<option value="icon-double-angle-up">double-angle-up</option>
<option value="icon-double-angle-down">double-angle-down</option>
<option value="icon-circle-blank">circle-blank</option>
<option value="icon-circle">circle</option>
<option value="icon-desktop">desktop</option>
<option value="icon-laptop">icon-laptop</option>
<option value="icon-tablet">tablet</option>
<option value="icon-mobile-phone">mobile-phone</option>
<option value="icon-quote-left">quote-left</option>
<option value="icon-quote-right">icon-quote-right</option>
<option value="icon-reply">reply</option>
<option value="icon-github-alt">github-alt</option>
<option value="icon-folder-close-alt">folder-close-alt</option>
<option value="icon-folder-open-alt">folder-open-alt</option>

